name: jardineritoapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  table_calendar: ^3.0.0
  uuid: ^4.0.0
  google_fonts: ^6.1.0 
  animate_do: ^4.2.0
  lottie: ^3.3.0
  http: ^1.1.0
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  flutter_zoom_drawer: ^3.0.3
  flutter_staggered_grid_view: ^0.7.0
  animated_text_kit: ^4.2.2
  provider: ^6.1.1
  flutter_svg: ^2.0.7
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  

# Sección específica de Flutter
flutter:
  assets:
    - assets/images/logo.png
    - assets/images/historial.png
    - assets/images/ayuda.png
    - assets/images/explorar.png
    - assets/images/plantas.png
    - assets/images/jardinerito.png
    - assets/images/lottie/sol.json
    - assets/images/lottie/lluvia.json
    - assets/images/lottie/nubes.json
    - assets/images/lottie/arboles.json
    - assets/images/lottie/ornamentales.json
    - assets/images/orna.png
    - assets/images/medi.png
    - assets/images/arb.png
    - assets/images/todas.png
    - assets/images/arboles.jpg
    - assets/images/titulo.jpg
    - assets/images/acuarelaverde.jpg
    - assets/images/acuarelarosa.jpg
    - assets/images/fondo.jpg
    - assets/images/fondo2.jpg



  uses-material-design: true




