// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJd50NbFeiUB2-bfC_Niq5ihgPWhD0xWs',
    appId: '1:328234171523:web:eba8e4d0c3c52520086fb6',
    messagingSenderId: '328234171523',
    projectId: 'jardinerito-c92bd',
    authDomain: 'jardinerito-c92bd.firebaseapp.com',
    storageBucket: 'jardinerito-c92bd.firebasestorage.app',
    measurementId: 'G-JDZSTR8XN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWgTr1LVoxvL7l4GkGi9F50E1ZnIaUXBw',
    appId: '1:328234171523:android:a5772acbcdf3fcb1086fb6',
    messagingSenderId: '328234171523',
    projectId: 'jardinerito-c92bd',
    storageBucket: 'jardinerito-c92bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNDcCkUBeyzk6xorVEkNiHwGPRqP49Chg',
    appId: '1:328234171523:ios:f42e493bfc6b4b29086fb6',
    messagingSenderId: '328234171523',
    projectId: 'jardinerito-c92bd',
    storageBucket: 'jardinerito-c92bd.firebasestorage.app',
    iosBundleId: 'com.example.jardineritoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNDcCkUBeyzk6xorVEkNiHwGPRqP49Chg',
    appId: '1:328234171523:ios:f42e493bfc6b4b29086fb6',
    messagingSenderId: '328234171523',
    projectId: 'jardinerito-c92bd',
    storageBucket: 'jardinerito-c92bd.firebasestorage.app',
    iosBundleId: 'com.example.jardineritoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJd50NbFeiUB2-bfC_Niq5ihgPWhD0xWs',
    appId: '1:328234171523:web:d04369f12e080b14086fb6',
    messagingSenderId: '328234171523',
    projectId: 'jardinerito-c92bd',
    authDomain: 'jardinerito-c92bd.firebaseapp.com',
    storageBucket: 'jardinerito-c92bd.firebasestorage.app',
    measurementId: 'G-7BRQL72473',
  );
}
